### ISSUE TITLE
Counting does not work as expected

### ISSUE THREAD

**Issue by k4nar** [pelotoncycle/peloton_bloomfilters#2]
Hello,

When using your library, I noticed something weird with the counter: It is always incremented, even when adding an existing value. Is it an expected behavior?

This means that if add the same value several times, the filter will eventually be cleared despite not being full. Here is an example:

``` python
In [1]: from peloton_bloomfilters import BloomFilter

In [2]: bf = BloomFilter(10, 0.001)

In [3]: bf.add(0)
Out[3]: False

In [4]: len(bf)
Out[4]: 1

In [5]: bf.add(0)
Out[5]: False

In [6]: len(bf)
Out[6]: 2

In [7]: [bf.add(x) for x in xrange(10)]
Out[7]: [False, False, False, False, False, False, False, False, True, False]

In [8]: 0 in bf
Out[8]: False

In [9]: 1 in bf
Out[9]: False

In [10]: 9 in bf
Out[10]: True
```

**Comment by adamdeprince** [comment]
Yes, this is the correct behaivor.   Bloomfilters provide probabilistic set membership, for any number you add, there are a great number of other numbers that will appear to be in the set by accident.     

Rather than guessing, I decided to leave it up to the user.   Testing and only incrementing the counter if the filter doesn't return true for membership requires more processing time.   I decided to instead leave it up to the user - if you don't want the `len` of the bloomfilter to grow, add items this way instead:

```
if x not in bf:
  bf.add()
```

This way users who don't want this test aren't forced to pay the compute overhead of having it.

**Comment by adamdeprince** [comment]
Its also worth pointing out in your example that you exceed the capacity of the bloomfilter in your loop.    This is why `0` and `1` are no longer members.   There are different things bloomfilter library authors can do in this situation.   I could have failed to add, raising an exception of some sort or the other.   I could have "grown" the bloomfilter http://gsd.di.uminho.pt/members/cbm/ps/dbloom.pdf.   Instead I just cleared it and rolled over with a fresh bloomfilter.   I did it this way because its simple, fast, and matches the business needs were at Peloton that motivated its creation - we use it for caching - I might write a paper on that at some point.   It wouldn't be too hard to subclass this and add other behaviors, including scaling.    I might do just that at some point.

**Comment by k4nar** [comment]
Ok, thanks, I understand. I figured out that this must be the reason, but I was hoping that maybe there was  a workaround around that besides checking for every item before adding it.

> Its also worth pointing out in your example that you exceed the capacity of the bloomfilter in your loop. This is why 0 and 1 are no longer members.

Yes, I understand your design decision and it's made pretty clear in the docs.

Thank you for your library anyways, in my benchmark this is the fastest Python bloom filter library out there!

**Comment by adamdeprince** [comment]
If you want that behavior in a bloomfilter, you'd have to do that check
yourself anyway.   ITs not a hard adaptation - your code would look
something like this

```
class YourBloomFilter(Bloomfilter):
  def __setitem__(self, key, value):
    if key not in self:
        super(YourBloomFilter, self).__setitem__(key, value)
```
